server:
  port: 8082
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:25432/banca_db
    username: banca_usr
    password: banca_pwd
---
logging:
  level:
    org.springframework.r2dbc: DEBUG